import { configureStore } from "@reduxjs/toolkit";
import authRecuder from "../redux/slices/authSlice";
import jobReducer from "../redux/slices/jobSlice";
import { authApi } from "../services/authApi";
import companyReducer from "../redux/slices/createCompanyProfileSlice";
import { companyApi } from "../services/companyApi";
import { jobsApi } from "../services/jobsApi";
import { paymentApi } from "../services/paymentApi";
import candidateReducer from "../redux/slices/userProfileSlice";
import { candidateApi } from "../services/candidateApi";
import themeReducer from "../redux/slices/themeSlice";

export const store = configureStore({
  reducer: {
    auth: authRecuder,
    theme: themeReducer,
    jobs: jobReducer,
    company: companyReducer,
    candidate: candidateReducer,
    // Add the RTK Query reducers
    // These reducers are automatically generated by RTK Query based on the endpoints defined in the services
    // They handle caching, invalidation, and other state management tasks for the API data
    // Each API service has its own reducer that needs to be added to the store
    // The reducerPath is the key under which the API state is stored in the Redux store
    // For example, authApi.reducerPath will store the state of the authApi service under
    [authApi.reducerPath]: authApi.reducer, // RTK Query reducer
    [companyApi.reducerPath]: companyApi.reducer,
    [jobsApi.reducerPath]: jobsApi.reducer,
    [paymentApi.reducerPath]: paymentApi.reducer,
    [candidateApi.reducerPath]: candidateApi.reducer,
  },

  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(
      authApi.middleware,
      companyApi.middleware,
      jobsApi.middleware,
      paymentApi.middleware,
      candidateApi.middleware
    ), // RTK Query middleware
});
//
